site_name: tam Docs
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Getting Started2: getting-started.md
  - Getting Started3: getting-started.md
  - Getting Started4: getting-started.md
theme:
  name: gitbook